import type { Metadata } from 'next';
import Link from 'next/link';

/**
 * /kundli
 *
 * The hero's primary action points here, so this route has to exist — a
 * primary CTA that 404s is worse than no CTA at all.
 *
 * What it deliberately does NOT do: show a chart, a form that discards input,
 * or a date picker that computes nothing. The Kundli engine is deferred past
 * first revenue, ProKerala is not wired up, and CLAUDE.md §71 forbids fake
 * calculations outside an explicit dev adapter. A page that says "not yet,
 * here is who to ask" is honest; one that draws an invented chart is not.
 *
 * When the engine lands (Phase 9+), this page becomes the real tool and the
 * copy below is replaced rather than added to.
 */

export const metadata: Metadata = {
  title: 'Kundli — Stella Astrology',
  description:
    'Birth chart readings with named, practising astrologers. The free Kundli tool is in preparation.',
  robots: { index: false, follow: false },
};

export default function KundliPage() {
  return (
    <>
      {/* The page gets a head and a body. Previously the eyebrow and H1 floated
          at the top-left of an empty ivory field, which is what made every
          interior route read as unfinished. */}
      <div className="masthead" lang="en">
        <div className="wrap">
          <p className="eyebrow">Kundli</p>
          <h1 className="pageTitle">Your birth chart, read by a person.</h1>
          <p className="pageLede">
            The free Kundli tool is being built. Until it is ready we are not
            going to show you a chart generated by something we have not yet
            validated — a birth chart is only worth reading if the calculation
            behind it is right.
          </p>
        </div>
      </div>

      <div className="page" lang="en">
      <div className="wrap">
        <p className="pageLede">
          In the meantime, our astrologers read charts directly. Write to us
          with your date, time and place of birth and we will come back to you.
        </p>

        <p className="pageActions">
          <a className="btn" href="mailto:guruji@stellaastro.com">
            guruji@stellaastro.com
          </a>
          <Link className="btnGhost" href="/">
            Back to home
          </Link>
        </p>

        <p className="pageNote">
          When the tool opens it will show the method, the ayanamsa and the
          engine version behind every chart, so a result can be checked rather
          than taken on trust.
        </p>
      </div>
      </div>
    </>
  );
}
